<?php

namespace Database\Seeders;

use App\Models\Task;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class TaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Task::create( [
            'id'=>1,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskaya',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640130672rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>6,
            'status'=>'finished',
            'created_at'=>'2021-12-21 08:09:54',
            'updated_at'=>'2021-12-21 19:51:12'
            ] );

            Task::create( [
            'id'=>2,
            'user_id'=>1,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskva',
            'address'=>'tverskaya',
            'task_description'=>'do your work correctl',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-21 08:10:59',
            'updated_at'=>'2021-12-21 08:10:59'
            ] );

            Task::create( [
            'id'=>3,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskva',
            'address'=>'tverskaya',
            'task_description'=>'do your work correctl',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'back.jpg',
            'views'=>NULL,
            'executor_profile_id'=>1,
            'status'=>'in process',
            'created_at'=>'2021-12-21 09:22:35',
            'updated_at'=>'2021-12-21 09:22:35'
            ] );

            Task::create( [
            'id'=>4,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskva',
            'address'=>'tverskaya',
            'task_description'=>'do your work correctl',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640128537back.jpg',
            'views'=>NULL,
            'executor_profile_id'=>6,
            'status'=>'finished',
            'created_at'=>'2021-12-21 19:15:37',
            'updated_at'=>'2021-12-21 19:15:37'
            ] );

            Task::create( [
            'id'=>5,
            'user_id'=>2,
            'title'=>'',
            'category_name'=>'remont',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskva',
            'address'=>'tverskaya',
            'task_description'=>'do your work correctl',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640128713parallax.html',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-21 19:18:33',
            'updated_at'=>'2021-12-21 19:18:33'
            ] );

            Task::create( [
            'id'=>6,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskva',
            'address'=>'tverskaya',
            'task_description'=>'do your work correctl',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640128874rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-21 19:21:14',
            'updated_at'=>'2021-12-21 19:21:14'
            ] );

            Task::create( [
            'id'=>7,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskaya',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640130935rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>3,
            'status'=>'finished',
            'created_at'=>'2021-12-21 19:55:35',
            'updated_at'=>'2021-12-21 19:55:35'
            ] );

            Task::create( [
            'id'=>8,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640131272rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-21 20:01:12',
            'updated_at'=>'2021-12-21 20:01:12'
            ] );

            Task::create( [
            'id'=>9,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640134172rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-21 20:49:32',
            'updated_at'=>'2021-12-21 20:49:32'
            ] );

            Task::create( [
            'id'=>10,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640135882rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-21 21:18:02',
            'updated_at'=>'2021-12-21 21:18:02'
            ] );

            Task::create( [
            'id'=>11,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640157432rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>5,
            'status'=>'finished',
            'created_at'=>'2021-12-22 03:17:12',
            'updated_at'=>'2021-12-22 03:17:12'
            ] );

            Task::create( [
            'id'=>12,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajner',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640162405rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-22 04:40:05',
            'updated_at'=>'2021-12-22 04:40:05'
            ] );

            Task::create( [
            'id'=>13,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn1',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640326808rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 02:20:08',
            'updated_at'=>'2021-12-24 02:20:08'
            ] );

            Task::create( [
            'id'=>14,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn1',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640327225rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 02:27:05',
            'updated_at'=>'2021-12-24 02:27:05'
            ] );

            Task::create( [
            'id'=>15,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn1',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640327485rest1.jpg',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 02:31:25',
            'updated_at'=>'2021-12-24 02:31:25'
            ] );

            Task::create( [
            'id'=>16,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn1',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'C:\\xampp\\tmp\\phpD985.tmp',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 02:37:19',
            'updated_at'=>'2021-12-24 02:37:19'
            ] );

            Task::create( [
            'id'=>17,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn1',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'C:\\xampp\\tmp\\php5AB7.tmp',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 02:38:58',
            'updated_at'=>'2021-12-24 02:38:58'
            ] );

            Task::create( [
            'id'=>18,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn3',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'C:\\xampp\\tmp\\php9429.tmp',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 03:14:10',
            'updated_at'=>'2021-12-24 03:14:10'
            ] );

            Task::create( [
            'id'=>19,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn5',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'C:\\xampp\\tmp\\phpBFA6.tmp',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 03:16:32',
            'updated_at'=>'2021-12-24 03:16:32'
            ] );

            Task::create( [
            'id'=>20,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn5',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'C:\\xampp\\tmp\\phpCAA6.tmp',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 03:30:47',
            'updated_at'=>'2021-12-24 03:30:47'
            ] );

            Task::create( [
            'id'=>21,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn5',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'C:\\xampp\\tmp\\php7733.tmp',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 03:31:31',
            'updated_at'=>'2021-12-24 03:31:31'
            ] );

            Task::create( [
            'id'=>22,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn5',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640334147bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 04:22:27',
            'updated_at'=>'2021-12-24 04:22:27'
            ] );

            Task::create( [
            'id'=>23,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn5',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640334301bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-24 04:25:01',
            'updated_at'=>'2021-12-24 04:25:01'
            ] );

            Task::create( [
            'id'=>24,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn5',
            'subcategory_name'=>'web-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'do your work correctly',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640503015bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-26 03:16:55',
            'updated_at'=>'2021-12-26 03:16:55'
            ] );

            Task::create( [
            'id'=>25,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn5',
            'subcategory_name'=>'interier-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640588054bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-27 02:54:14',
            'updated_at'=>'2021-12-27 02:54:14'
            ] );

            Task::create( [
            'id'=>26,
            'user_id'=>5,
            'title'=>'',
            'category_name'=>'services dizajn5',
            'subcategory_name'=>'interier-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640588159bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-27 02:55:59',
            'updated_at'=>'2021-12-27 02:55:59'
            ] );

            Task::create( [
            'id'=>27,
            'user_id'=>4,
            'title'=>'',
            'category_name'=>'services dizajn5',
            'subcategory_name'=>'interier-dizainer',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>0,
            'price_to'=>0,
            'task_location'=>'y klienta',
            'task_img'=>'1640679437bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2021-12-28 04:17:17',
            'updated_at'=>'2021-12-28 04:17:17'
            ] );

            Task::create( [
            'id'=>28,
            'user_id'=>4,
            'title'=>'remont',
            'category_name'=>'services dizajn6',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641445379bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-06 01:02:59',
            'updated_at'=>'2022-01-06 01:02:59'
            ] );

            Task::create( [
            'id'=>29,
            'user_id'=>4,
            'title'=>'remont',
            'category_name'=>'services dizajn7',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641802213bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>7,
            'status'=>'false',
            'created_at'=>'2022-01-10 04:10:14',
            'updated_at'=>'2022-01-10 04:10:14'
            ] );

            Task::create( [
            'id'=>30,
            'user_id'=>4,
            'title'=>'remont',
            'category_name'=>'services dizajn10',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641811466bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-10 06:44:26',
            'updated_at'=>'2022-01-10 06:44:26'
            ] );

            Task::create( [
            'id'=>31,
            'user_id'=>4,
            'title'=>'remont',
            'category_name'=>'services dizajn12',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641811769bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-10 06:49:29',
            'updated_at'=>'2022-01-10 06:49:29'
            ] );

            Task::create( [
            'id'=>32,
            'user_id'=>4,
            'title'=>'remont',
            'category_name'=>'services dizajn14',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641812393bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-10 06:59:53',
            'updated_at'=>'2022-01-10 06:59:53'
            ] );

            Task::create( [
            'id'=>33,
            'user_id'=>4,
            'title'=>'remont',
            'category_name'=>'services dizajn14',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641812717bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>8,
            'status'=>'finished',
            'created_at'=>'2022-01-10 07:05:17',
            'updated_at'=>'2022-01-10 07:05:17'
            ] );

            Task::create( [
            'id'=>34,
            'user_id'=>24,
            'title'=>'remont',
            'category_name'=>'services dizajn14',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641812890bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>6,
            'status'=>'false',
            'created_at'=>'2022-01-10 07:08:10',
            'updated_at'=>'2022-01-10 07:08:10'
            ] );

            Task::create( [
            'id'=>35,
            'user_id'=>4,
            'title'=>'remont',
            'category_name'=>'services dizajn16',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641891207bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-11 04:53:27',
            'updated_at'=>'2022-01-11 04:53:27'
            ] );

            Task::create( [
            'id'=>36,
            'user_id'=>4,
            'title'=>'remont',
            'category_name'=>'services dizajn16',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641891286bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>8,
            'status'=>'finished',
            'created_at'=>'2022-01-11 04:54:46',
            'updated_at'=>'2022-01-11 04:54:46'
            ] );

            Task::create( [
            'id'=>37,
            'user_id'=>22,
            'title'=>'remont',
            'category_name'=>'services dizajn16',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641891326bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>7,
            'status'=>'finished',
            'created_at'=>'2022-01-11 04:55:26',
            'updated_at'=>'2022-01-11 04:55:26'
            ] );

            Task::create( [
            'id'=>38,
            'user_id'=>24,
            'title'=>'remont',
            'category_name'=>'services dizajn16',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1641891384bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-11 04:56:24',
            'updated_at'=>'2022-01-11 04:56:24'
            ] );

            Task::create( [
            'id'=>39,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn16',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>'1642415103bedroomSlider.png',
            'views'=>NULL,
            'executor_profile_id'=>9,
            'status'=>'finished',
            'created_at'=>'2022-01-17 06:25:03',
            'updated_at'=>'2022-01-17 06:25:03'
            ] );

            Task::create( [
            'id'=>40,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn16',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-20 22:13:58',
            'updated_at'=>'2022-01-20 22:13:58'
            ] );

            Task::create( [
            'id'=>41,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn17',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-20 22:22:25',
            'updated_at'=>'2022-01-20 22:22:25'
            ] );

            Task::create( [
            'id'=>42,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn17',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-20 22:23:10',
            'updated_at'=>'2022-01-20 22:23:10'
            ] );

            Task::create( [
            'id'=>43,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn17',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-20 22:23:36',
            'updated_at'=>'2022-01-20 22:23:36'
            ] );

            Task::create( [
            'id'=>44,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn17',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-20 22:24:52',
            'updated_at'=>'2022-01-20 22:24:52'
            ] );

            Task::create( [
            'id'=>45,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn17',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-20 22:25:42',
            'updated_at'=>'2022-01-20 22:25:42'
            ] );

            Task::create( [
            'id'=>46,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn17',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-20 22:27:16',
            'updated_at'=>'2022-01-20 22:27:16'
            ] );

            Task::create( [
            'id'=>47,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn17',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-20 22:27:59',
            'updated_at'=>'2022-01-20 22:27:59'
            ] );

            Task::create( [
            'id'=>48,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn17',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-20 22:28:38',
            'updated_at'=>'2022-01-20 22:28:38'
            ] );

            Task::create( [
            'id'=>49,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn17',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-20 22:30:46',
            'updated_at'=>'2022-01-20 22:30:46'
            ] );

            Task::create( [
            'id'=>50,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn18',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 00:25:41',
            'updated_at'=>'2022-01-21 00:25:41'
            ] );

            Task::create( [
            'id'=>51,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn18',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 02:30:15',
            'updated_at'=>'2022-01-21 02:30:15'
            ] );

            Task::create( [
            'id'=>52,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn18',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 02:37:50',
            'updated_at'=>'2022-01-21 02:37:50'
            ] );

            Task::create( [
            'id'=>53,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn18',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 02:40:13',
            'updated_at'=>'2022-01-21 02:40:13'
            ] );

            Task::create( [
            'id'=>54,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn18',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 02:41:41',
            'updated_at'=>'2022-01-21 02:41:41'
            ] );

            Task::create( [
            'id'=>55,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn18',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 02:43:46',
            'updated_at'=>'2022-01-21 02:43:46'
            ] );

            Task::create( [
            'id'=>56,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn18',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 02:45:36',
            'updated_at'=>'2022-01-21 02:45:36'
            ] );

            Task::create( [
            'id'=>57,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn18',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 02:49:11',
            'updated_at'=>'2022-01-21 02:49:11'
            ] );

            Task::create( [
            'id'=>58,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn19',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 02:50:55',
            'updated_at'=>'2022-01-21 02:50:55'
            ] );

            Task::create( [
            'id'=>59,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn19',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 02:55:17',
            'updated_at'=>'2022-01-21 02:55:17'
            ] );

            Task::create( [
            'id'=>60,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn19',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 03:04:06',
            'updated_at'=>'2022-01-21 03:04:06'
            ] );

            Task::create( [
            'id'=>61,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn19',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 03:08:03',
            'updated_at'=>'2022-01-21 03:08:03'
            ] );

            Task::create( [
            'id'=>62,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn19',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 03:10:57',
            'updated_at'=>'2022-01-21 03:10:57'
            ] );

            Task::create( [
            'id'=>63,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn19',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 03:13:33',
            'updated_at'=>'2022-01-21 03:13:33'
            ] );

            Task::create( [
            'id'=>64,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn19',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 07:14:08',
            'updated_at'=>'2022-01-21 07:14:08'
            ] );

            Task::create( [
            'id'=>65,
            'user_id'=>54,
            'title'=>'remont',
            'category_name'=>'services dizajn19',
            'subcategory_name'=>'interier-dizainer6',
            'region'=>'Moskvaaaa',
            'address'=>'tverskayaaaaa',
            'task_description'=>'My home must be individual',
            'task_starttime'=>'2021-12-21',
            'task_finishtime'=>'2021-12-30',
            'price_from'=>1000,
            'price_to'=>1500,
            'task_location'=>'y klienta',
            'task_img'=>NULL,
            'views'=>NULL,
            'executor_profile_id'=>NULL,
            'status'=>'false',
            'created_at'=>'2022-01-21 07:15:39',
            'updated_at'=>'2022-01-21 07:15:39'
            ] );
    }
}
