<?php

return [

    /*
    |--------------------------------------------------------------------------
    | STATIC STRINGS TRANSLATIONS
    |--------------------------------------------------------------------------
    |
    |  !!! WARNING - This is a file generated by the LanguagesService. !!!
    |  You should not modify it, as it shall be replaced next time this service is executed.
    |
     */

    'accepted' => ':attribute պետք է ընդունվի։',
    'accepted-if' => ':attribute պետք է ընդունվի, երբ :other :value է:',
    'active-url' => ':attribute վավեր URL չէ:',
    'after' => ':attribute պետք է լինի :date -ից հետո ամսաթիվ:',
    'after-or-equal' => ':attribute պետք է լինի :date -ին հաջորդող ամսաթիվ կամ հավասար:',
    'alpha' => ':attribute պետք է պարունակի միայն տառեր:',
    'alpha-dash' => ':attribute պետք է պարունակի միայն տառեր, թվեր, գծիկներ և ընդգծումներ:',
    'alpha-num' => ':attribute պետք է պարունակի միայն տառեր և թվեր:',
    'array' => ':attribute պետք է լինի զանգված:',
    'ascii' => ':attribute պետք է պարունակի միայն մեկ բայթանոց ալֆան-թվային նիշեր և նշաններ:',
    'before' => ':attribute պետք է լինի :date -ից առաջ ամսաթիվ:',
    'before_or_equal' => ':attribute պետք է լինի :date -ին նախորդող կամ հավասար ամսաթիվ:',
    'after_or_equal' => ':attribute պետք է լինի :date -ին հաջորդող կամ հավասար ամսաթիվ:',
    'date_format' => ':attribute ձևաչափն անվավեր է:',
    'between' => [
        'array' => ':attribute պետք է ունենա :min և :max տարրերի միջև:',
        'file' => ':attribute պետք է լինի :min և :max կիլոբայթների միջև:',
        'numeric' => ':attribute պետք է լինի :min -ի և :max -ի միջև:',
        'string' => ':attribute պետք է լինի :min և :max նիշերի միջև:',
    ],
    'boolean' => ':attribute դաշտը պետք է լինի true կամ false:',
    'confirmed' => ':attribute հաստատումը չի համընկնում:',
    'current-password' => 'Գաղտնաբառը սխալ է:',
    'date' => ':attribute վավեր ամսաթիվ չէ:',
    'date-equals' => ':attribute պետք է լինի :date -ին հավասար ամսաթիվ:',
    'date-format' => ':attribute չի համապատասխանում :format ձևաչափին:',
    'decimal' => ':attribute պետք է ունենա :decimal տասնորդական թվեր:',
    'declined' => ':attribute պետք է մերժվի:',
    'declined-if' => ':attribute պետք է մերժվի, երբ :other -ը :value է:',
    'different' => ':attribute -ը և :other -ը պետք է տարբեր լինեն։',
    'digits' => ':attribute պետք է լինի :digits թվանշան:',
    'digits-between' => ':attribute պետք է լինի :min և :max թվանշանների միջև:',
    'dimensions' => ':հատկանիշն ունի պատկերի անվավեր չափեր:',
    'distinct' => ':attribute դաշտը կրկնօրինակված արժեք ունի:',
    'doesnt-end-with' => ':attribute չի կարող ավարտվել հետևյալներից որևէ մեկով. :values',
    'doesnt-start-with' => ':attribute չի կարող սկսվել հետևյալներից որևէ մեկով. :values',
    'email' => ':attribute պետք է վավեր էլփոստի հասցե լինի:',
    'ends-with' => ':attribute պետք է ավարտվի հետևյալներից մեկով. :values',
    'enum' => 'Ընտրված :հատկանիշն անվավեր է:',
    'exists' => 'Ընտրված :հատկանիշն անվավեր է:',
    'file' => ':attribute պետք է լինի ֆայլ:',
    'filled' => ':attribute դաշտը պետք է արժեք ունենա:',
    'gt' => [
        'array' => ':attribute պետք է ունենա ավելի քան :value տարրեր:',
        'file' => ':attribute պետք է լինի :value կիլոբայթից մեծ:',
        'numeric' => ':attribute պետք է լինի :value -ից մեծ:',
        'string' => ':attribute պետք է մեծ լինի :value նիշերից:',
    ],
    'gte' => [
        'array' => ':attribute պետք է ունենա :value տարրեր կամ ավելին:',
        'file' => ':attribute պետք է մեծ կամ հավասար լինի :value կիլոբայթին:',
        'numeric' => ':attribute պետք է մեծ կամ հավասար լինի :value -ին:',
        'string' => ':attribute պետք է մեծ կամ հավասար լինի :value նիշերին:',
    ],
    'image' => ':attribute պետք է լինի պատկեր:',
    'in' => 'Ընտրված :attribute անվավեր է:',
    'in-array' => ':attribute դաշտը գոյություն չունի :other -ում:',
    'integer' => ':attribute պետք է լինի ամբողջ թիվ։',
    'ip' => ':attribute պետք է լինի վավեր IP հասցե:',
    'ipv4' => ':attribute պետք է լինի վավեր IPv4 հասցե:',
    'ipv6' => ':attribute պետք է լինի վավեր IPv6 հասցե:',
    'json' => ':attribute պետք է լինի վավեր JSON տող:',
    'lowercase' => ':attribute պետք է լինի փոքրատառ:',
    'lt' => [
        'array' => ':attribute պետք է ունենա :value -ից պակաս տարրեր.',
        'file' => ':attribute պետք է լինի :value կիլոբայթից փոքր.',
        'numeric' => ':attribute պետք է լինի :value -ից փոքր։',
        'string' => ':attribute պետք է լինի փոքր :value նիշերից.',
    ],
    'lte' => [
        'array' => ':attribute չպետք է ունենա ավելի քան :value տարրեր։',
        'file' => ':attribute պետք է լինի :value կիլոբայթից փոքր կամ հավասար:',
        'numeric' => ':attribute պետք է լինի փոքր կամ հավասար :value -ին:',
        'string' => ':attribute պետք է լինի փոքր կամ հավասար :value նիշերին:',
    ],
    'mac-address' => ':attribute պետք է լինի վավեր MAC հասցե:',
    'max' => [
        'array' => ':attribute չպետք է ունենա ավելի քան :max տարրեր:',
        'file' => ':attribute չպետք է լինի :max կիլոբայթից մեծ:',
        'numeric' => ':attribute չպետք է լինի :max -ից մեծ:',
        'string' => ':attribute չպետք է լինի :max նիշից մեծ:',
    ],
    'max-digits' => ':attribute չպետք է ունենա ավելի քան :max թվանշան:',
    'mimes' => ':attribute պետք է լինի :values ​​տեսակի ֆայլ:',
    'mimetypes' => ':attribute պետք է լինի :values ​​տեսակի ֆայլ:',
    'min' => [
        'array' => ':attribute պետք է ունենա առնվազն :min տարրեր.',
        'file' => ':attribute պետք է լինի առնվազն :min կիլոբայթ.',
        'numeric' => ':attribute պետք է լինի առնվազն :min.',
        'string' => ':attribute պետք է լինի առնվազն :min նիշ.',
    ],
    'min-digits' => ':attribute պետք է ունենա առնվազն :min թվանշաններ:',
    'missing' => ':attribute դաշտը պետք է բացակայի:',
    'missing-if' => ':attribute դաշտը պետք է բացակայի, երբ :other -ը :value է:',
    'missing-unless' => ':attribute դաշտը պետք է բացակայի, եթե :other -ը :value չէ:',
    'missing-with' => ':attribute դաշտը պետք է բացակայի, երբ առկա է :values:',
    'missing-with-all' => ':attribute դաշտը պետք է բացակայի, երբ առկա են :values:',
    'multiple-of' => ':attribute պետք է լինի :value -ի բազմապատիկ:',
    'not-in' => 'Ընտրված :հատկանիշն անվավեր է:',
    'not-regex' => ':attribute ձևաչափն անվավեր է:',
    'numeric' => ':attribute պետք է լինի թիվ։',
    'password' => [
        'letters' => ':attribute պետք է պարունակի առնվազն մեկ տառ:',
        'mixed' => ':attribute պետք է պարունակի առնվազն մեկ մեծատառ և մեկ փոքրատառ:',
        'numbers' => ':attribute պետք է պարունակի առնվազն մեկ թիվ։',
        'symbols' => ':attribute պետք է պարունակի առնվազն մեկ նշան:',
        'uncompromised' => 'Տվյալ :attribute հայտնվել է տվյալների արտահոսքի մեջ: Խնդրում ենք ընտրել այլ :attribute :',
    ],
    'present' => ':attribute դաշտը պետք է լինի:',
    'prohibited' => ':attribute դաշտն արգելված է:',
    'prohibited-if' => ':attribute դաշտն արգելված է, երբ :other -ը :value է:',
    'prohibited-unless' => ':attribute դաշտն արգելված է, եթե :other-ը :values -ում չէ:',
    'prohibits' => ':attribute դաշտն արգելում է :other -ին ներկա լինել:',
    'regex' => ':attribute ձևաչափն անվավեր է:',
    'required' => ':attribute դաշտը պարտադիր է:',
    'required-array-keys' => ':attribute դաշտը պետք է պարունակի գրառումներ՝ :values -ի համար:',
    'required-if' => ':attribute դաշտը պարտադիր է, երբ :other-ը :value է:',
    'required-if-accepted' => ':attribute դաշտը պարտադիր է, երբ :other ընդունված է:',
    'required-unless' => ':attribute դաշտը պարտադիր է, եթե :other -ը :values-ում չէ:',
    'required-with' => ':attribute դաշտը պահանջվում է, երբ առկա է :values:',
    'required-with-all' => ':attribute դաշտը պահանջվում է, երբ առկա են :values:',
    'required-without' => ':attribute դաշտը պահանջվում է, երբ :values ​​չկա:',
    'required-without-all' => ':attribute դաշտը պարտադիր է, երբ :value -ներից ոչ մեկը չկա:',
    'same' => ':attribute -ը և :other -ը պետք է համապատասխանեն:',
    'size' => [
        'array' => ':attribute պետք է պարունակի :size տարրեր:',
        'file' => ':attribute պետք է լինի :size կիլոբայթ:',
        'numeric' => ':attribute պետք է լինի :size :',
        'string' => ':attribute պետք է լինի :size նիշ:',
    ],
    'starts-with' => ':attribute պետք է սկսվի հետևյալներից մեկով. :values :',
    'string' => ':attribute պետք է լինի տող:',
    'timezone' => ':attribute պետք է վավեր ժամային գոտի լինի:',
    'unique' => ':attribute արդեն գոյություն ունի։',
    'uploaded' => 'Չհաջողվեց վերբեռնել :attribute :',
    'uppercase' => ':attribute պետք է լինի մեծատառ:',
    'url' => ':attribute պետք է լինի վավեր URL:',
    'ulid' => ':attribute պետք է լինի վավեր ULID:',
    'uuid' => ':attribute պետք է լինի վավեր UUID:',
    'custom' => '',
    'attributes' => '',
    'empty-field' => 'Լրացնել առնվազն մեկ դաշտ',
    'result-not-found' => 'Արդյունք չի գտնվել',
    'empty-seria-number' => 'Համար կամ սերիա դաշտը դատարկ է',
    'there-is-a-limit' => 'Առկա է սահմանափակում',
    'not-found' => 'Արդյունք չի գտնվել',
    'language' => 'Լեզու',
    'email-or-password-is-incorrect' => 'էլ. փոստը կամ գաղտնաբառը սխալ է',
    'generated-fail' => 'գեներացված համարանիշ չկա',
    'Vehicle-has-not-been-registered' => 'տվյալ Տրանսպորտային Միջոցը հաշվառում չի անցել',
    'you-dont-have-permition'=>'Դուք չունեք համապատասխան թույլտվություն մուտք գործելու համար',


    /*
    |--------------------------------------------------------------------------
    | Custom Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | Here you may specify custom validation messages for attributes using the
    | convention "attribute.rule" to name the lines. This makes it quick to
    | specify a specific custom language line for a given attribute rule.
    |
     */

    'custom' => [
        // 'attribute-name' => [
        //     'rule-name' => 'custom-message',
        // ],
        'true-answer' => [
            'required' => 'Շրջանակներից որևէ մեկի ընտրությունը պարտադիր է',
        ],
        'answer_options.*.text'=>[
            'required'=>'Պատասխանների տարբերակների  դաշտերը պարտադիր են'
        ],
        'license_plantes'=>[
            'required' =>'Տվյալ պահին բազայում բացակայում է ազատ Պետ․ համարանիշի սերիա, Գեներացնել նորը'

        ],
        'already_exists'=>[
            'required' => 'Մուտքագրված տեխնիկական վկայագրի սերիան  արդեն գոյություն ունի',
        ],
        'authorized_person'=>[
            'required' =>'Տեխ․վկայագրում նշվող անձի ընտրությունը պարտադիր է:',

        ],
        'file_name'=>[
            'required' =>  'Համապատասխան պետական տուրքի վճարի անդորագրի կցումը պարտադիր է',
        ],

        'provision_of_duplicate' => [
            'required' => 'Շրջանակներից որևէ մեկի ընտրությունը պարտադիր է',
        ],

        'driving_license_already_exists'=> [
            'required' => 'Վարման վկայականը արդեն գոյություն ունի:',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Custom Validation Attributes
    |--------------------------------------------------------------------------
    |
    | The following language lines are used to swap our attribute placeholder
    | with something more reader friendly such as "E-Mail Address" instead
    | of "email". This simply helps us make our message more expressive.
    |
     */

    'attributes' => [
        'key' => 'Lեզու',
        'sections' => 'Բաժին',
        'new_section' => 'Բաժին',
        'tag' => 'Թեգ',
        'permission_name' => 'Գործիք',
        'permission' => 'Գործիք',
        'name' => 'Անուն',
        'description' => 'Նկարագրություն',
        'edit_description'=> 'Նկարագրություն',
        'edit_vehicle_type_name' => 'Անուն',
        'edit_name' => 'Անուն',
        'edit_vehicle_mark'=> 'Անուն',
        'questionnaire_language_id'=> 'Հարցաշարի լեզվի',
        'content'=>' ',
        'name1' => 'Անուն',
        'accounting_name' => 'Անուն',
        'group' => 'Խումբ',
        'groups' => 'Խումբ',
        'type'=>'Տեսակ',
        'question_type'=>'Հարցի տեսակ',
        'last_name' => 'Ազգանուն',
        'middle_name' => 'Հայրանուն',
        'email' => 'Էլ․ հասցե',
        'password' => 'Գաղտնաբառ',
        'required_password' => 'Գաղտնաբառի հաստատում',
        'roles' => 'Դեր',
        'languages_id' => 'Լեզու',
        'document_type_id' =>'Հիմք փաստաթուղթ',
        'price'=>'ԳՏ վաճառքի արժեք',
        'owner.*.type'=>'Անձի կարգավիճակ',
        'transaction_type' => 'Գործարքի տեսակ',
        'vehicle_mark_id' => 'Մակնիշ',
        'vehicle_model_id' => 'Մոդել',
        'sub_color_id' => 'Գույն',
        'vehicle_date' => 'Տարեթիվ',
        'identification_number' => 'Նույնացման համար',
        'engine_type' => 'Շարժիչի տեսակ',
        'fuel_type' => 'Վառելիքի տեսակ',
        'engine_power_hp' => 'Շարժիչի հզորություն (Ձ/Ու)',
        'engine_power_kw' => 'Շարժիչի հզորություն (կՎ)*',
        'vehicle_cateories_id' => 'ՏՄ տեսակ',
        'equipment_type_id' => 'Սարքինության տեսակ',
        'edit_groups' => 'Խումբ',
        'license_plate_seria' => 'Սերիա',
        'license_plate_number' => 'Համար',
        'start_date' => 'Սահմանափակման սկիզբ',
        'end_date' => 'Սահմանափակման ավարտ',
        'structure' => 'Կառույց',
        'reason_restriction' => 'Սահմանափակման պատճառ',
        'second_name' => 'Ազգանուն',
        'family_name' => 'Հայրանուն',
        'birthdate' => 'Ծննդյան ամսաթիվ',
        'birth_place' => 'Ծննդյան վայր',
        'citizenship' => 'Քաղաքացիություն',
        'address' => 'Հասցե',
        'passport' => 'Անձնագիր',
        'given_by' => 'Ում կողմից է տրված',
        'when_issued' => 'Երբ է տրված',
        'public_service_number' => 'ՀԾՀ',
        'phone_number' => 'Հեռախոսահամար',
        'type_of_process' => 'Գործընթացի տեսակ',
        'data.owner.0.type'=>'Անձի կարգավիճակ',
        'data.owner.*.name' => 'Անուն',
        'data.owner.*.second_name' => 'Ազգանուն',
        'data.owner.*.citizenship' => 'Քաղաքացիություն',
        'data.owner.*.doc_type' => 'Փաստաթղթի տեսակը',
        'data.owner.*.passport' => 'Փաստաթղթի համարը',
        'data.owner.*.given_by' => 'Ում կողմից է տրված',
        'data.owner.*.when_issued' => 'Երբ է տրված',
        'data.owner.*.public_service_number' => 'ՀԾՀ',
        'data.owner.*.birthdate' => 'Ծննդյան ամսաթիվ',
        'data.owner.*.gender' => 'Սեռ',
        'data.owner.*.community' => 'Համայնք/Վարչ․շրջան',
        'data.owner.*.residence' => 'Բնակավայր',
        'data.owner.*.postalsorter' => 'Փոստային դասիչ',
        'data.owner.*.building' => 'Շենք',
        'data.owner.*.phone_number' => 'Հեռախոսահամար',
        'data.owner.*.email' => 'Էլ․փոստ',
        'data.juridical_person.*.legal_person_address' => 'Իրավաբանական անձի հասցեն',
        'data.juridical_person.*.state_registry' => 'Պետական գրանցման ռեգիստր',
        'data.juridical_person.*.taxpayer_identification_number' => 'ՀՎՀՀ',
        'data.juridical_person.*.legal_person_number' => 'Իրավաբանական անձի հեռախոսահամար',
        'data.juridical_person.*.name' => 'Իրավաբանական անձի տնօրենի անուն',
        'data.juridical_person.*.second_name' => 'Իրավաբանական անձի տնօրենի ազգանուն',
        'data.juridical_person.*.passport' => 'Իրավաբանական անձի տնօրենի փաստաթղթի համար',
        'data.juridical_person.*.given_by' => 'Ում կողմից է տրված',
        'data.juridical_person.*.when_issued' => 'Երբ է տրված',
        'data.juridical_person.*.public_service_number' => 'Իրավաբանական անձի տնօրենի ՀԾՀ',
        'data.juridical_person.*.phone_number' => 'Իրավաբանական անձի տնօրենի hեռախոսահամար',
        'data.authorized_person.0.name'=>'Լիազորված անձի անուն',
        'data.authorized_person.0.second_name' => 'Լիազորված անձի ազգանուն',
        'data.authorized_person.0.family_name' => 'Լիազորված անձի հայրանուն',
        'data.authorized_person.0.citizenship' => 'Լիազորված անձի քաղաքացիություն',
        'data.authorized_person.0.doc_type' => 'Լիազորված անձի փաստաթղթի տեսակ',
        'data.authorized_person.0.passport' => 'Լիազորված անձի փաստաթղթի համար',
        'data.authorized_person.0.given_by' => 'Լիազորված անձի փաստաթղթի ում կողմից է տրված',
        'data.authorized_person.0.when_issued' => 'Լիազորված անձի փաստաթղթի տրման ամսաթիվ',
        'data.authorized_person.0.public_service_number' => 'Լիազորված անձի ՀԾՀ',
        'data.authorized_person.0.birthdate' => 'Լիազորված անձի ծննդյան ամսաթիվ',
        'data.authorized_person.0.gender' => 'Լիազորված անձի սեռ',
        'data.authorized_person.0.community' => 'Լիազորված անձի  համայնք/վարչ․շրջան',
        'data.authorized_person.0.residence' => 'Լիազորված անձի բնակավայր',
        'data.authorized_person.0.building' => 'Լիազորված անձի շենք',
        'data.authorized_person.0.phone_number'=>'Լիազորված անձի hեռախոսահամար',
        'data.authorized_person.0.email' => 'Լիազորված անձի էլ․փոստ',


        'counting_place' =>'Օպերատորի հաշվառման վայր',
        'plate_value' =>'Համարանիշի տեսակ',
        'technical_pass_seria_number' => 'Տեխնիկական վկայագրի սերիա համար',
        'license_plantes_id' => 'Պետ․ համարանիշի սերիա համար',
        'all_nessary_action'=> 'Կատարել եք բոլոր անհրաժեշտ գործողությունների',
        'all_document_circulation'=>'Կատարել եք համապատասխան փաստաթղթաշրջանառության',
        'doc_type'=>'Փաստաթղթի տեսակը',
        'path'=> 'Կցել փաստաթղթեր',
        'property_code'=>'Գույքի ծածկագիր/կոդ/',
        'transaction_code'=>'Գործարքի ծածկագիր',
        'engine_number' => 'Շարժիչի համար',
        'instrument_number' => 'Հենասարքի համար',
        'use_the_system_template'=>'Օգտվել համակարգի ձևանմուշից',

        'counting_place_id' => 'Տրման վայր',
        'accounting_application_id' => 'Հայտ',
        'driving_classification_id' => 'Խումբ / Խմբերի բաժին',
        'exam' => 'Քննություն',
        'signature'=>'Ստորագրող անձի ստորագրությունը',

        'choose_type' => 'Տեսակ',
        'mass_min' => 'ՏՄ զանգված առանց բեռվնածության կգ',
        'signature' => 'Ստորագրություն',
        'phone_number_valid_type' => 'Հեռախոսահամար',
        'response_technical_passport_serie_number'=> 'Տեխնիկական վկայագրի սերիա համար',
        'responce_plate_number'=> 'Պետ․ համարանիշի սերիա համար',
        'vehicle_category_id'=>'ՏՄ տեսակի ընտրություն',
        'date'=>'Ամսաթիվ',
        'drivers_license_number' => 'Վարորդական վկայականի համարը',

        'plate_type' => 'ՏՄ տեսակի համարանիշ',

        'license_plate' => 'Համարանիշ',
        'amount'=>'Գումար',
        'license_plate_type' => 'Համարանիշի տեսակ',
        'mass_max' => 'ՏՄ առավելագույն զանգված կգ',
        'seats_number' => 'Նստատեղերի քանակ',
        'vehicle_subcategory_id' => 'ՏՄ Ենթատեսակ',
        'file' => 'Կցել փաստաթղթեր',
        'files' => 'Կցել փաստաթղթեր',
        'unreason_restriction' => 'Սահմանափակումից հանելու պատճառ',

        'seria' => 'Համարանիշի սերիա',
        'number' => 'Համարանիշի համար',

        'count' => 'Համարանիշների քանակ',


    ],

];
